### ISSUE TITLE
Changing port in config breaks example

### ISSUE THREAD

**Issue by LaurensRietveld** [zazukoians/trifid-ld#1]
The resources in the example dataset use port 8080. I.e., running trifid-ld on a different port breaks the example

**Comment by bergos** [comment]
Thank you @LaurensRietveld for you feedback. Trifid-LD uses now the new RDF-Ext namespace map method to replace the default host+port with the one in the configuration file. (Don't forget npm update rdf-ext!)

**Comment by retog** [comment]
Does this mean the resources in the dataset should always be in the http://localhost:8080/ namespace regardless of host/port trifid-ld actually listens to? Also how exactly do I configure host+port and protocl (http/https)?

**Comment by bergos** [comment]
The http://localhost:8080 namespace mapping is part of the init function. You have to adapt it to your data.

@retog The configuration change a little bit in the meantime. It also contains now some comments. Can I close this issue?

**Comment by retog** [comment]
Looking at the current config.js it seems much more self-explanatory. So I think this can be closed.
