### ISSUE TITLE
YASGUI HTML should be implemented with a template and the endpoint URL should be read from the configuration

### ISSUE THREAD

**Issue by bergos** [zazukoians/trifid-ld#15]
The [HTML file](https://github.com/zazukoians/trifid-ld/blob/master/data/public/sparql/index.html#L16) for YASGUI contains hardcoded the endpoint URL. With a template, the server could replace the string with an URL from the configration. First it should check the SparqlProxy settings, than the SparqlHandler settings: 

```
config.sparqlProxy.options.endpointUrl || config.handlerOptions.endpointUrl
```

**Comment by ktk** [comment]
Evaluate if we do that with RDF2h

**Comment by bergos** [comment]
Implemented with [this commit](https://github.com/zazukoians/trifid-ld/commit/135576d6bfa2e29c75b5ef8e5d12a3a8bf2ae2e1).
