### ISSUE TITLE
Provide links to the predicates in RDF2h based output

### ISSUE THREAD

**Issue by ktk** [zazukoians/trifid-ld#17]
Currently the predicates cannot be clicked in the RDF2h based output.

**Comment by retog** [comment]
Not sure for two reasons:
- it seems more intuitive to browse from node to node
- Unfortunately not all properties are dereferenceable (ok,that also applies to subject/object)

**Comment by ktk** [comment]
In development of SPARQL queries I constantly click on the predicate. Often I get a full Turtle or worse RDF/XML file back but that's still better than having to copy the URI manually and then doing the same thing in a new window.

If I know the predicate I don't click on it but I copy the URI. This is much faster and more reliable than selecting the string first in the browser and then copying it.

**Comment by retog** [comment]
fixed.
