### ISSUE TITLE
Umlauts broken in HTML rendering

### ISSUE THREAD

**Issue by ktk** [zazukoians/trifid-ld#19]
It seems that Umlauts are still broken in current release, see for example:

http://environment.data.admin.ch/ubd/28/qb/ubd28

**Comment by bergos** [comment]
It's already [fixed](https://github.com/rdf-ext/rdf-graph-array/blob/master/index.js#L141), the rdf2h distribution must be updated.

**Comment by ktk** [comment]
Now fixed in Trifid-LD with commit https://github.com/zazukoians/trifid-ld/commit/902f59031320631677a2aa805e1ded83e2d90c50
