### ISSUE TITLE
well-known ports 

### ISSUE THREAD

**Issue by retog** [zazukoians/trifid-ld#2]
The readme says:

> Note that it is not recommended to run Node applications on well-known ports (< 1024). 

Shouldn't this speak about "privileged" rather than "well-known" ports.

http://www.w3.org/Daemon/User/Installation/PrivilegedPorts.html

**Comment by ktk** [comment]
I thought so as well before I wrote the Readme. However, IANA says well-known ports or system ports:

https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers#Well-known_ports
