### ISSUE TITLE
Use config.default.js only as fallback

### ISSUE THREAD

**Issue by bergos** [zazukoians/trifid-ld#29]
By default `config.js` should be used, which should not be part of the default Trifid-LD repository. If that file doesn’t exist `config.default.js` should be used.

[LDApp](https://github.com/bergos/ldapp/blob/master/ldapp.js#L4) implements this already.

**Comment by ktk** [comment]
`config.js` overrides values in `config.default.js`. One will need both configs in most cases. `config.default.js` is in git while `config.js` is in `.gitignore`

**Comment by bergos** [comment]
With the new [command line interface](https://github.com/zazukoians/trifid-ld/commit/0e1e525314463b3a78d81a2fc9e4fc5da7e642f7) this issue is deprecated.
