### ISSUE TITLE
Add/create module to redirect request to build IRIs different to the requested IRI

### ISSUE THREAD

**Issue by bergos** [zazukoians/trifid-ld#32]
There should be a package to patch the request object to redirect requests to a different IRI.

**Comment by ktk** [comment]
It should rewrite IRIs in request and response (response only when named node in RDF)

**Comment by bergos** [comment]
Implemented with [this commit](https://github.com/zazukoians/trifid-ld/commit/161a2ba15a5494f6d2eba1c93a448ae3ff896877) in the dev branch.
