### ISSUE TITLE
Rendering with blank nodes broken

### ISSUE THREAD

**Issue by ktk** [zazukoians/trifid-ld#33]
The rendering of blank nodes looks pretty weird, see the attached screenshot

Sample URI: http://environment.data.admin.ch/ubd/28/qb/dsd_ubd28
- the `http://purl.org/linked-data/cube#order` attribute only shows up on the first one, but it's attached to all of them
- the int-value of this attribute is directly glued to the predicate
- the alignment is broken, looks different all the time

![screen shot 2016-05-30 at 15 05 42](https://cloud.githubusercontent.com/assets/583021/15650327/0313a838-2678-11e6-8f0c-2b632e0d5746.png)

**Comment by retog** [comment]
@alemela the problem I see is that the cube:order property is only shown on the first blank node.

**Comment by retog** [comment]
Fixed by #34
