### ISSUE TITLE
HTML version to contain json-ld instead of turtle

### ISSUE THREAD

**Issue by retog** [zazukoians/trifid-ld#46]
Blocked by: https://github.com/rdf2h/ld2h/issues/1

Verify meta-data visibility with https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fclassifications.data.admin.ch%2Fmunicipality%2F371

**Comment by ktk** [comment]
Seems to require a CDN version of the json-ld parser for inclusion and some minimal changes on RDF2h

**Comment by retog** [comment]
The CDN rdf-ldp-store I think includes json-ls already: https://github.com/retog/rdf-store-ldp-browser
