### ISSUE TITLE
Rename config.fuseki.json to config.sparql.json

### ISSUE THREAD

**Issue by ktk** [zazukoians/trifid-ld#52]
So it looks more generic

**Comment by l00mi** [comment]
Hm, that makes no sense? This was introduced because you wanted to have multiple configs for different stores.. there will be a config.stardog.json and config.virtuos.json later on.

**Comment by ktk** [comment]
I don't think that makes sense for most stuff in the options. The stuff which is different for SPARQL endpoints is quite small, mostly about the DESCRIBE statement and possible auth. Duplicating the whole config for that looks like overkill to me.

**Comment by l00mi** [comment]
What was exactly we argued in the meeting in Biel. So I hope @bergos will not be angry of reverting.

**Comment by bergos** [comment]
Fixed in the dev branch with [this commit](https://github.com/zazukoians/trifid-ld/commit/64fde82fb68a1bd9c0ee8532e9500c955a58a88a). If we need a Fuseki config, we can use the new "baseConfig" feature and just replace values of the query values.
