### ISSUE TITLE
Rollback UI rendering in last commit

### ISSUE THREAD

**Issue by ktk** [zazukoians/trifid-ld#7]
Can we please rollback the UI stuff introduced in the last commit 74eb55462c613cd4f394fa4d131009df5053c0b? I do not want to introduce namespaces & names that will change and it does not yet provide the same functionality of the existing UI by @bergos.

This should either be removed or moved to a separate branch for the moment.

**Comment by ktk** [comment]
After checking the commits I'm not sure if this was just the last commit. I mean the RDF2H rendering.

**Comment by retog** [comment]
Which functionality of the UI by @bergos are you missing?

**Comment by ktk** [comment]
Can we not get into these discussions now and just roll it back? Was an accident anyway according to what you told me. We can have this discussions once I have more time.

**Comment by ktk** [comment]
What I saw in the 2 seconds I tested it:
- date is not formated
- uses full page, no border or anything
- does not embed JSON-LD by default which I want due to SEO support for it

**Comment by retog** [comment]
I've created a branch called `pre-docker` which does not contain the thing's I've recently added (but does contain @bergos recent bug fix). Changing the master would be a bad option as this branch is build by dockerhub and the gont.ch project depends on that.

**Comment by retog** [comment]
Please create new issues for the functionality missing in master.

**Comment by retog** [comment]
If you want docker but no rdf2h the `pre-rdf2h` branch is for you.
